### ISSUE TITLE
Add no-UMI option

### ISSUE THREAD

**Issue by dladd** [nf-core/airrflow#127]
It could be useful to be able to use bcellmagic on datasets without UMIs.

I was thinking of using the [Greiff2014_Workflow data subset from the presto docs](https://presto.readthedocs.io/en/stable/workflows/Greiff2014_Workflow.html) as a minimal/test example for development.

**Comment by ggabernet** [comment]
Hi @dladd , that would definitely be a great option for the pipeline!

**Comment by alaindomissy** [comment]
I am very interested in such an option !

**Comment by ggabernet** [comment]
This issue has been solved by #128
