### ISSUE TITLE
Trouble running bcellmagic

### ISSUE THREAD

**Issue by aislinnjennings** [nf-core/airrflow#138]
Hi.

I'm a new user and I'm trying to follow the Takara Bio TCR workflow.
However I'm having trouble with memory requirements.
 I'm getting the following error:

Error executing process > 'NFCORE_BCELLMAGIC:BCELLMAGIC:FETCH_DATABASES (IMGT IGBLAST)'

Caused by:
  Process requirement exceed available memory -- req: 12 GB; avail: 8 GB

Command executed:

  fetch_databases.sh
  echo $(date "+%F") > IMGT.version.txt

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /Volumes/Hard drive/bcellmagic/work/db/c293fe251fb5decf6087e4940e22a7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Would you have any ideas please?

Thanks so much.
Aislinn.

**Comment by ggabernet** [comment]
Hi @aislinnjennings , could you share the command that you used to run the pipeline?

You can try adding the parameters `--max_cpus <N cpus available> --max_memory 8.GB`. However typically the calculations performed by this pipeline require more memory to run so you might need to execute it in a high performance cluster infrastructure or a machine with higher memory available.

**Comment by ggabernet** [comment]
Hi @aislinnjennings,
I will close this due to inactivity but please feel free to re-open the issue if it persists
