### ISSUE TITLE
Dowser lineages `igphyml` when using `r-enchantr=0.0.3`

### ISSUE THREAD

**Issue by ggabernet** [nf-core/airrflow#198]
### Description of the bug

There is an error in the `Dowser lineages` process when running the pipeline with the test profile (uses `r-enchantr 0.0.3`)

### Command used and terminal output

```console
run nf-core/airrflow -r airrflow -profile test,docker --outdir "results" -resume


label: unnamed-chunk-2
Quitting from lines 124-159 (_main.Rmd)
Error in buildIgphyml(data, igphyml = exec, temp_path = file.path(dir,  :
  The file /usr/local/share/igphyml/src/igphyml cannot be executed.
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> getTrees -> buildIgphyml
In addition: Warning messages:
1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘enchantr’
2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘enchantr’
3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘enchantr’
4: In buildIgphyml(data, igphyml = exec, temp_path = file.path(dir,  :
  Dowser igphyml doesn't mask split codons!
```
```


### Relevant files

_No response_

### System information

nextflow version 22.10.2.5832

**Comment by ggabernet** [comment]
I've checked within the `enchantr 0.0.3` container and `igphyml` is installed in another path:

```
(base) [qeaga01@thanos test-raw]$ docker run -it quay.io/biocontainers/r-enchantr:0.0.3--r42hdfd78af_1
sh-5.0# /usr/local/share/igphyml/src/igphyml
sh: /usr/local/share/igphyml/src/igphyml: No such file or directory
sh-5.0# which igphyml
/usr/local/bin/igphyml
sh-5.0#
```

**Comment by toobiwankenobi** [comment]
N E X T F L O W  ~  version 23.04.1
  nf-core/airrflow v3.1.0-ga2a6099

`nextflow run nf-core/airrflow -profile test,singularity `

**Comment by andreiprodan** [comment]
Hi @ggabernet ! I'm also testing airrflow now and ran into the same issue with running with -profile test,singularity. I checked the **depot.galaxyproject.org-singularity-r-enchantr-0.1.2--r42hdfd78af_0.img** image and igphyml path is  **/usr/local/bin/igphyml**. However, running the test pipeline with "--igphyml /usr/local/bin/igphyml" does not prevent the error: 

```
> processing file: _main.Rmd
>   |.................................                  |  64% [unnamed-chunk-3]
> Quitting from lines 136-216 [unnamed-chunk-3] (_main.Rmd)
> Error in `value[[3L]]()`:
> Backtrace:
>  1. dowser::getTrees(...)
> Warning messages:
> 1: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'enchantr'
> 2: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'enchantr'
> 3: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'enchantr'
```

**Comment by andreiprodan** [comment]
` nextflow run nf-core/airrflow -profile test,singularity --outdir output_test    --skip_all_clones_report` still crashes in the same process

**Comment by ggabernet** [comment]
Hi, sorry the documentation is wrong, this parameter default is updated both in the master and dev branch to match the container:
https://github.com/nf-core/airrflow/blob/a2a6099a9e73cca504f3e33b566ddb997acdb7b5/nextflow.config#L84

I think the error you are getting is related to something else but not the `igphyml` executable path. We are currently investigating this error.
