### ISSUE TITLE
IMGT/GENE-DB downloads failing

### ISSUE THREAD

**Issue by mdeboth** [nf-core/airrflow#273]
### Description of the bug

I'm running nf-core/airrflow for the first time; no IMGT database is cached locally.
It fails with error:
```
Command error:
  BLAST options error: File igblast_base/fasta/imgt_human_ig_c.fasta is empty
  BLAST options error: File igblast_base/fasta/imgt_human_ig_d.fasta is empty
  BLAST options error: File igblast_base/fasta/imgt_human_ig_j.fasta is empty
  ...
  BLAST options error: File igblast_base/fasta/imgt_aa_mouse_tr_v.fasta is empty
```

It seems if I try to run the [fetch_imgt.sh](https://github.com/nf-core/airrflow/blob/a2a6099a9e73cca504f3e33b566ddb997acdb7b5/bin/fetch_imgt.sh) script manually, wget is failing to download from imgt.org.

**Comment by bshim181** [comment]
It seems like the imgt.org database is down currently. I am having the same issue as well. I was wondering if anyone could upload a copy of the previously downloaded data (TR and IG for human).

**Comment by mdeboth** [comment]
Hey @bshim181 - Try running the [bin/fetch_imgt.sh](https://github.com/nf-core/airrflow/blob/dev/bin/fetch_imgt.sh) script from the dev branch.
Those imgt.org URLs worked for me.
