### ISSUE TITLE
test data failing

### ISSUE THREAD

**Issue by andreiprodan** [nf-core/airrflow#275]
### Description of the bug

I've downloaded the test_full dataset locally (files and parameters  from the 'metadata_pcr_umi_airr_300.tsv' from the test_full.config file) and ran the pipeline using the singularity profile (added Slurm executor to the singularity profile). 

`nextflow run ./airrflow -profile hpc --outdir output_full_test --input input_test_full/metadata_pcr_umi_airr_300.tsv --cprimers input_test_full/cprimers.fasta --vprimers input_test_full/vprimers.fasta --imgtdb_base input_test_full/imgtdb_base.zip --igblast_base input_test_full/igblast_base.zip --library_generation_method  specific_pcr_umi --cprimer_position R1 --umi_length 15 --umi_start 0 --umi_position R1`

Execution crashes at the CLONAL_ANALYSIS:DOWSER_LINEAGES process with the following error:

```
Error executing process > 'NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES (SRR1383452)'

Caused by:
  Process `NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES (SRR1383452)` terminated with an error exit status (1)

Command executed:

  Rscript -e "enchantr::enchantr_report('dowser_lineage', \
                                          report_params=list('input'='SRR1383452__clone-pass.tsv', \
                                          'exec'='/usr/local/bin/igphyml', \
                                          'outdir'=getwd(), \
                                          'nproc'=16,\
                                          'log'='SRR1383452_dowser_command_log' ,'build'='igphyml'))"

      echo "NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES": > versions.yml
      Rscript -e "cat(paste0('  enchantr: ',packageVersion('enchantr'),'
  '))" >> versions.yml

      mv enchantr 'SRR1383452_dowser_report'

Command exit status:
  1

Command output:
  1/14
  2/14 [global-options]
  3/14
  4/14 [input-parameters]
  5/14 [unnamed-chunk-1]
  6/14
  7/14 [unnamed-chunk-2]
  8/14
  9/14 [unnamed-chunk-3]

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred


  processing file: _main.Rmd

  Quitting from lines 136-216 [unnamed-chunk-3] (_main.Rmd)
  Error in `value[[3L]]()`:
  Backtrace:
   1. dowser::getTrees(...)
  Warning messages:
  1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘enchantr’
  2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘enchantr’
  3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘enchantr’
  Execution halted
```

### System information

HPC running Slurm
Singularity
RockyOS
Nextflow version 22.10.1 build 5828
airrflow v.3.1.0

**Comment by ggabernet** [comment]
Hi @andreiprodan , thank you for opening the issue. I have investigated this and it seems like this error occurs only when using the singularity container and not with the docker container. I am working on a more permanent fix, but as as a workaround, could you try whether running the same command but with the following configuration file works:

```
nextflow run nf-core/airrflow -r 3.1.0 <other parameters you are using> -c custom.config
```

with the custom.config file containing the following:
```
process{
  withName: DOWSER_LINEAGES {
    ext.singularity_pull_docker_container = true
  }
}
```
This forces pulling the docker container which currently works and converting it to singularity at runtime. We are also working towards a fix for the singularity container itself.

**Comment by mdeboth** [comment]
I'm seeing the same error, also running Slurm + Singularity.
Pulling the docker container doesn't seem help.
I'm not too familiar with airrflow yet, so still trying to narrow down the issue.
