### ISSUE TITLE
Analyzing BCR Rep-Seq Data in nf-core/airrflow Without Primer Information

### ISSUE THREAD

**Issue by pengjiao** [nf-core/airrflow#277]
### Description of feature

Hello,

I'm working with BCR Rep-Seq data and I have the resulting FASTQ files along with UMI information. However, I do not have the primer information for my samples. Would you have any recommendations or suggestions on how I can proceed with the data analysis using the nf-core/airrflow pipeline without the primer details? Any guidance would be greatly appreciated.

Thank you in advance!

**Comment by ggabernet** [comment]
Hi @pengjiao , 
yes indeed the BCR Rep-seq data requires knowing the primer information for processing unfortunately. Sometimes it is possible to guess the primers by doing a sequence alignment of the reads, for example with ClustalW

**Comment by ggabernet** [comment]
I will close this issue, but if you have further questions on how to find the primers you can continue asking here. We also have a slack channel that can be more useful for this kind of discussions: https://nf-co.re/join
