### ISSUE TITLE
Isotype and c_call columns

### ISSUE THREAD

**Issue by eba28** [nf-core/airrflow#303]
### Description of feature

It would be great to have an `Isotype` column that generates from the `c_call` column e.g. IgA, IgD, IgE, IgG, IgM. The `c_call` column right now can return multiple genes like IgBLAST does, but for plotting it's nice to just have the overall family e.g. "IGHA2" instead of "IGHA2\*01,IGHA2\*02" . Perhaps there can be a new column (if you don't want to overwrite `c_call`) that uses [`alakazam::getFamily`](https://alakazam.readthedocs.io/en/latest/topics/getSegment/) to get this information? This function includes options for keeping multiple calls.

**Comment by ggabernet** [comment]
Very good point @eba28, I worked on adding this on the `enchantr` package side, and I'll close this issue once the new version is added to airrflow

**Comment by eba28** [comment]
The AIRR standard for `c_call` does say to include the allele: [Rearrangement Schema](https://docs.airr-community.org/en/latest/datarep/rearrangements.html#fields). So perhaps there should be a new column for the family instead of updating the `c_call` column? Not sure if we ever check for this in the Immcantation pipeline.

**Comment by ggabernet** [comment]
Hi @eba28, this is added already in the `dev` branch of the pipeline. The isotype is added in the `isotype` column now, while the `c_call` is mantained intact. It will be available in the next release!
