### ISSUE TITLE
AIRRflow error/fails at Dowser step

### ISSUE THREAD

**Issue by margaretc-ho** [nf-core/airrflow#309]
Hi there,

I'm new to using AIRRFlow and Nextflow and I was trying to run some B cell sequencing (10X Genomics, AIRR formatted data) through the AIRRflow pipeline. First, I was able to run the pipeline on the test data before I tried it with our data. With our data, I am able to get parts of the pipeline to run but I get an error during the CLONAL_ANALYSIS:DOWSER_LINEAGES step. The command I used to run the pipeline was 

```
nextflow run nf-core/airrflow -profile biowulf --input Ainhoa_BCR_SampleSheet.tsv --mode assembled  --outdir Ainhoa_BCR_results
```

When I go to the work directory indicated (/spin1/home/linux/homc/Ainhoa_BCR_data/AIRRdata/work/22/8bdd61484c139132783f18b51a7ff3) it is empty. Please see error message below.

```
Nextflow workflow report
[reverent_rutherford]
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES (subject_x)'

Caused by:
  Process `NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES (subject_x)` terminated with an error exit status (1)

Command executed:

  Rscript -e "enchantr::enchantr_report('dowser_lineage', \
                                          report_params=list('input'='subject_x__clone-pass.tsv', \
                                          'exec'='/usr/local/share/igphyml/src/igphyml', \
                                          'outdir'=getwd(), \
                                          'nproc'=16,\
                                          'log'='subject_x_dowser_command_log' ,'build'='igphyml','minseq'=5,'tips'='c_call','traits'='c_call'))"
  
      cp -r enchantr subject_x_dowser_report && rm -rf enchantr
  
      echo "NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:DOWSER_LINEAGES": > versions.yml
      Rscript -e "cat(paste0('  enchantr: ',packageVersion('enchantr'),'
  '))" >> versions.yml

Command exit status:
  1

Command output:
  1/18                   
  2/18 [global-options]  
  3/18                   
  4/18 [input-parameters]
  5/18 [unnamed-chunk-1] 
  6/18                   
  7/18 [read-repertoires]
  8/18                   
  9/18 [formatClones]    
  10/18                   
  11/18 [getTrees]        
  12/18                   
  13/18 [plotTrees]       

Command error:
  
  
  processing file: _main.Rmd
  
  Quitting from lines 222-246 [plotTrees] (_main.Rmd)
  Error in `names(pal) <- as.character(unique(states))`:
  ! 'names' attribute [17] must be the same length as the vector [8]
  Backtrace:
   1. dowser::plotTrees(trees, tips = tips, tipsize = 2)
   2. dowser::getPalette(tipstates, tip_palette)
  Warning messages:
  1: replacing previous import 'data.table::last' by 'dplyr::last' when loading 'enchantr' 
  2: replacing previous import 'data.table::first' by 'dplyr::first' when loading 'enchantr' 
  3: replacing previous import 'data.table::between' by 'dplyr::between' when loading 'enchantr' 
  Execution halted

Work dir:
  /spin1/home/linux/homc/Ainhoa_BCR_data/AIRRdata/work/22/8bdd61484c139132783f18b51a7ff3

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Can anyone help point me in the right direction to try and troubleshoot this? I also attached the .nextflow.log below

### Relevant files

[nextflow.log](https://github.com/nf-core/airrflow/files/14465143/nextflow.log)
[execution_report_2024-03-01_13-13-06.zip](https://github.com/nf-core/airrflow/files/14465161/execution_report_2024-03-01_13-13-06.zip)

### System information

nextflow version 23.10.0.5889
Hardware: HPC (NIH Biowulf cluster)
Executor: SLURM

lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.7 (Green Obsidian)
Release:        8.7
Codename:       GreenObsidian

I believe this should be the latest AIRRflow version 3.2.0

**Comment by ggabernet** [comment]
Hi @margaretc-ho , 

thanks for reporting this issue. This is due to a color palette used in Dowser, and it should have been solved  in the new release of Airrflow. Would you mind trying it out with the new release specifying the `-r 3.3.0`  parameter?

**Comment by margaretc-ho** [comment]
@ggabernet when I try running with -r 3.3.0 parameter it says that it can't find this version in the AIRRflow repository?

nextflow run nf-core/airrflow -r 3.3.0 -profile biowulf --input SampleSheet.tsv --mode assembled  --outdir BCR_results
N E X T F L O W  ~  version 23.10.0
Cannot find revision `3.3.0` -- Make sure that it exists in the remote repository `https://github.com/nf-core/airrflow`

**Comment by margaretc-ho** [comment]
@ggabernet Unfortunately the `-r dev` flag didn't work either. This is the error I get when trying that.

```
    ERROR ~ Error executing process > 'NFCORE_AIRRFLOW:AIRRFLOW:CHANGEO_CONVERTDB_FASTA_FROM_AIRR (1)'                            
Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-mulled-v2-7d8e418eb73acc6a80daea8e111c94cf19a4ecfd-a9ee25632c9b10bbb012da76e6eb539acca8f9cd-1.img.pulling.1712009822237 https://depot.galaxyproject.org/singularity/mulled-v2-7d8e418eb73acc6a80daea8e111c94cf19a4ecfd:a9ee25632c9b10bbb012da76e6eb539acca8f9cd-1 > /dev/null
  status : 143
  message:
    INFO:    Downloading network image
 -- Check '.nextflow.log' file for details
```

Do you have advice of how to properly pull the correct version? Since `-r 3.3.0` was not able to work.

**Comment by margaretc-ho** [comment]
@ggabernet It worked! At first I had trouble running it, but I used the following commands to specifically get the 3.3.0 release

```
nextflow pull nf-core/airrflow -r 3.3.0
nextflow run nf-core/airrflow -r 3.3.0 -profile biowulf --input Ainhoa_BCR_SampleSheet.tsv --mode assembled  --outdir AinhoaBCR_results
```

At least for me, I need the pull command first in order to properly retrieve the correct version. I was able to run the pipeline and it completed successfully. Thank you!!

**Comment by ggabernet** [comment]
Hi Margaret, great ti hear thank you! Let me know if you have any further
issues or questions, and sorry for the late reply as I am currenly away
