### ISSUE TITLE
How to draw a similar flowchart in the Pipeline summary section

### ISSUE THREAD

**Issue by LiuH2020** [nf-core/airrflow#318]
### Description of the bug

Hello. The message conveyed by the flowchart in the Pipeline summary section is intuitive and clear. I'm interested in learning how to create a similar flowchart for a pipeline. Could you please share some tips or experiences with me? For example, what software was used to create it, or what is this type of image called so that I can search for relevant information? Thank you. Additionally, I apologize for submitting an issue with  bug labels.
![flowchart](https://github.com/nf-core/airrflow/raw/master/docs/images/metro-map-airrflow.png)

**Comment by ggabernet** [comment]
Hi @LiuH2020,

this diagram was manually drawn in inkscape, using some of the design icons provided as part of nf-core: /gpfs/gibbs/pi/kleinstein/gg647/panos2024/results

I hope this is useful!
