### ISSUE TITLE
Installation issues - airrflow pipeline

### ISSUE THREAD

**Issue by pnatarajan9** [nf-core/airrflow#341]
### Description of the bug

Airrflow - https://github.com/nf-core/airrflow

CRITICAL The container "nf-core/cellranger:7.1.0" is unavailable.                                                                    
         WARNING: Couldn't use cached digest for registry: HEAD https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0:       
         unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)                                  
         WARNING: Falling back to direct digest.                                                                                     
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                    
         docker://nf-core/cellranger:7.1.0: GET https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0: UNAUTHORIZED:         
         authentication required; [map[Action:pull Class: Name:nf-core/cellranger Type:repository]]   

### System information

Nextflow version - 23.04.1
nf-core version: 2.7.2
Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-28-generic x86_64)
nf-core airrflow version 4.1.0

**Comment by pnatarajan9** [comment]
**Full command used and the errors:**

$ nf-core download airrflow --outdir dev --singularity-cache-only  --container singularity

? Select release / branch: 4.1.0  [release]

If transferring the downloaded files to another system, it can be convenient to have everything compressed in a single file.
This is not recommended when downloading Singularity images, as it can take a long time and saves very little space.
? Choose compression type: none
INFO     Saving 'nf-core/airrflow'                                                                                                     
          Pipeline revision: '4.1.0'                                                                                                   
          Pull containers: 'singularity'                                                                                               
          Using $NXF_SINGULARITY_CACHEDIR': /ccbbcoded/ccbb_software/software/nfcore/singularity                                       
          Output directory: 'dev'                                                                                                      
INFO     Downloading workflow files from GitHub                                                                                        
INFO     Downloading centralised configs from GitHub                                                                                   
INFO     Found 12 containers                                                                                                           
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━  92% • 11/12 completed
nf-core/cellranger:7.1.0 WARNING: Falling back to direct digest. ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━  92% • 11/12 completed
nf-core/cel… FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://nf-cor… INFO     WARNING: Couldn't use cached digest for registry: HEAD https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0:         
         unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)                                    
         WARNING: Falling back to direct digest.                                                                                       
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                      
         docker://nf-core/cellranger:7.1.0: GET https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0: UNAUTHORIZED:           
         authentication required; [map[Action:pull Class: Name:nf-core/cellranger Type:repository]]                                    
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━  92% • 11/12 completed
nf-core/cel… FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://nf-cor… 
CRITICAL The container "nf-core/cellranger:7.1.0" is unavailable.                                                                      
         WARNING: Couldn't use cached digest for registry: HEAD https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0:         
         unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)                                    
         WARNING: Falling back to direct digest.                                                                                       
         FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for                      
         docker://nf-core/cellranger:7.1.0: GET https://index.docker.io/v2/nf-core/cellranger/manifests/7.1.0: UNAUTHORIZED:           
         authentication required; [map[Action:pull Class: Name:nf-core/cellranger Type:repository]]

**Comment by ggabernet** [comment]
Hi @pnatarajan9,

I tested this command with the latest version of the nf-core tools (`2.14.1`) and it is working for me:

```
nf-core download airrflow --outdir dev --container-system singularity

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

    nf-core/tools version 2.14.1 - https://nf-co.re


WARNING  Could not find GitHub authentication token. Some API requests may fail.                                                                   
? Select release / branch: 4.1.0  [release]
? Include the nf-core's default institutional configuration files into the download? No

Nextflow and nf-core can use an environment variable called $NXF_SINGULARITY_CACHEDIR that is a path to a directory where remote Singularity images
are stored. This allows downloaded images to be cached in a central location.
? Define $NXF_SINGULARITY_CACHEDIR for a shared Singularity image download folder? [y/n]: 
Please enter Y or N
? Define $NXF_SINGULARITY_CACHEDIR for a shared Singularity image download folder? [y/n]: n

If transferring the downloaded files to another system, it can be convenient to have everything compressed in a single file.
This is not recommended when downloading Singularity images, as it can take a long time and saves very little space.
? Choose compression type: tar.gz
INFO     Saving 'nf-core/airrflow'                                                                                                                 
          Pipeline revision: '4.1.0'                                                                                                               
          Use containers: 'singularity'                                                                                                            
          Container library: 'quay.io'                                                                                                             
          Output file: 'dev.tar.gz'                                                                                                                
          Include default institutional configuration: 'False'                                                                                     
INFO     Downloading workflow files from GitHub                                                                                                    
INFO     Processing workflow revision 4.1.0, found 13 container images in total.                                                                   
Pulling singularity images ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% • 13/13 completed
INFO     Compressing output into archive                                                                                                           
INFO     Command to extract files: tar -xzf dev.tar.gz                                                                                             
INFO     MD5 checksum for 'dev.tar.gz': 2d325c504ef1632a7627b0ea6048abf9 
```
Inside the tar archive the cellranger container was also downloaded properly. Did you try updating the nf-core tools?

**Comment by pnatarajan9** [comment]
Update: We were able to install airrflow with the nf-core version 2.14.1 in different compute environment. Thank you for your help!

**Comment by ggabernet** [comment]
Great to hear that your issue has been solved!
