### ISSUE TITLE
find_threshold in enchantr_report with TCR data fails

### ISSUE THREAD

**Issue by zhanyinx** [nf-core/airrflow#345]
### Description of the bug

The distToNearest function within enchantr::enchantr_report function in the task NFCORE_AIRRFLOW:AIRRFLOW:CLONAL_ANALYSIS:FIND_CLONAL_THRESHOLD returns only NA values for distance as the default value for locusValues within distToNearest is set to "IGH". For TCR data, we expect these values: c("TRA", "TRB", "TRD", "TRG"). It should be made possible to change this parameter in the configuration file.

### Command used and terminal output

The pipeline runs without problem with the expected output

```
Automatic clone_threshold is 'NA'. Consider setting --clonal_threshold manually.
```

The command used:
```
nextflow run nf-core/airrflow
		 -r 4.1.0
		 -profile singularity
		 --mode fastq
		 --input samplesheet.tsv
		 --library_generation_method sc_10x_genomics
		 --reference_10x refdata-cellranger-vdj-GRCh38-alts-ensembl-7.1.0
		 --outdir ./results_auto
		 -with-tower
		 --index_file
```
```


### Relevant files

_No response_

### System information

nextflow version 23.10.1.5891
Hardware: server
Executor: local
Container: singularity
OS: CentOS Linux
nf-core/airrflow version: 4.1

**Comment by ggabernet** [comment]
Hi @zhanyinx,

sorry for the late reply! For TCR data, we expect clones to have the same CDR3, so you can directly set the parameters `--clonal_threshold 0`, and `--skip_report_threshold` to skip finding the clonal threshold.

We'll add a check  for future versions that this is automatically set for TR locus analysis.

**Comment by ggabernet** [comment]
I'll close the issue but feel free to reopen it if you have any further questions!
