### ISSUE TITLE
Check whether file compressed or not

### ISSUE THREAD

**Issue by fabio-t** [nf-core/airrflow#89]
It would be nice if the pipeline didn't crash when using plain FASTQ files, rather than gzipped ones :)

Not a huge deal, but it's not specified into the documentation (or I missed it).

**Comment by ggabernet** [comment]
Hi @fabio-t ,
thanks for the suggestion, gzipped fastqs are the most common input formats now but it's right that this should be at least documented or support for `fastq` files added.

**Comment by ggabernet** [comment]
Closing this as we decided to support only gzipped files for this pipeline, let us know if you have any other issues!
